### ISSUE TITLE
Sandbox refactor 

### ISSUE THREAD

**Issue by dmay23** [sciath/sciath#18]
Can we refactor sandbox such that all it's functionality is confined entirely to only the harness and have it not poke into Test? If that requires redesigning the Test object - fine. Since the sandbox seems to primarily manipulate paths (or streams), maybe it should be copying existing tests and redefining their paths and running within a new instance of Harness.

**Comment by psanan** [comment]
Mostly done with #37, but should take another look to see if things can be improved (since so far I just refactored the existing logic).
