### ISSUE TITLE
Resolve any stray TODOs

### ISSUE THREAD

**Issue by psanan** [sciath/sciath#41]
Remove/resolve any remaining TODOs, which should never be present in release code. (These should in theory be covered by other issues, so this issue is just a final check that things haven't been overlooked).

**Comment by dmay23** [comment]
Can you just do it?

**Comment by psanan** [comment]
I just created this so I could add it to a later milestone, since I think it's very likely some TODOs will creep in, or some old ones that are there now will escape notice. (Sorry for the noise!)

**Comment by psanan** [comment]
CodeFactor will alert to these
