### ISSUE TITLE
Assess Python 2 compatibility requirements and add Python 2 test to CI

### ISSUE THREAD

**Issue by psanan** [sciath/sciath#56]
It'd be great to be able to deprecate Python 2 with the rest of the world, but it's almost certain that clusters we care about will still have Python 2 for a while, so we should make sure that SciATH still works with Python 2 and thus have an automated test of this.  This shouldn't be hard with Travis: https://docs.travis-ci.com/user/languages/python/#specifying-python-versions

**Comment by psanan** [comment]
Actually, maybe this is up for debate.. Python 2 is officially deprecated/sunset as of two weeks ago. Obviously any effort spent on supporting Python 2 is effort that could be directed elsewhere, so I'm very tempted to just abandon Python 2 entirely. @dmay23 do you have an opinion on this?

**Comment by dmay23** [comment]
On Thu, 16 Jan 2020 at 10:13, Patrick Sanan <notifications@github.com>
wrote:

> Actually, maybe this is up for debate.. Python 2 is officially
> deprecated/sunset as of two weeks ago.
>
Yes - long live python3

> Obviously any effort spent on supporting Python 2 is effort that could be
> directed elsewhere, so I'm very tempted to just abandon Python 2 entirely.
> @dmay23 <https://github.com/dmay23> do you have an opinion on this?
>

RIP python2

In reality thought, deprecated doesn't really mean it will disappear from
our perspective. There are still old machines around running py2 and
until those systems die, or get a major OS upgrade py2 will persist in our
world.

I would not purge all py2 code from sciath. I would definitely keep py3 the
default and where we are aware of existing code which is not compat with
py2, we keep those fall backs in place. I certainly wouldn't spend any time
on actively keeping it py2 compat. Rather I would just add patches here and
there if and when they arise.

**Comment by psanan** [comment]
Yeah, I like the approach we are going for with the `subprocess` stuff. Prioritize the Python 3 way of doing things, and override when needed with Python 2 compatible stuff (which on some golden day in the future, will all be stripped out). To keep things moving, then, I'm not going to worry about keeping things working continuously with Python 2, but when possible try to keep notes about what isn't expected to be compatible, so that compatibility can be restored once the refactoring is done.
