### ISSUE TITLE
Remove PyYAML dependency

### ISSUE THREAD

**Issue by psanan** [sciath/sciath#87]
This is now the only module being used that isn't standard. Removing it would be very attractive, since SciATH is hoped to be useful on clusters where this module wouldn't be trivial to obtain.

The module is used to parse very simple YAML files, so a custom parser isn't at all out of the question, just a little bit of work.

**Comment by psanan** [comment]
We could approach this by just directly including another module or script which parses YAML, e.g
https://github.com/bionikspoon/pureyaml
or maybe even PyYAML itself

**Comment by psanan** [comment]
Whatever is done here, it can (and should) be done first with MiniSciATH, which is used for the self-tests.

**Comment by psanan** [comment]
While we're at this, we might also consider changing the configuration files to use YAML (just means changing `key=` to `key:`, I think), so that we only have to have one file-parser.

**Comment by dmay23** [comment]
I like this idea.

**Comment by psanan** [comment]
pureyaml is looking less attractive now, because it hasn't been touched in 4 years, and it doesn't work out of the box for me.

**Comment by dmay23** [comment]
Try strictyaml
Worked for me

**Comment by psanan** [comment]
I didn't find that one - what a beautiful package! I really love how it clearly focuses on what we actually want YAML for:
- config files in block format, ignore flow styles (just use JSON)
- all data are strings by default, no confusing implicit type conversions

I was just about to integrate it until I realized that it depends on another non-standard package, `ruamel.yaml`  : (

**Comment by dmay23** [comment]
On Mon, 15 Jun 2020 at 07:28, Patrick Sanan <notifications@github.com>
wrote:

> I didn't find that one - what a beautiful package! I really love how it
> clearly focuses on what we actually want YAML for:
>
>    - config files in block format, ignore flow styles (just use JSON)
>    - all data are strings by default, no confusing implicit type
>    conversions
>
> I was just about to integrate it until I realized that it depends on
> another non-standard package, ruamel.yaml : (
>

Ah damn - I didn't know that either.
I use ruamel and it is good (actually it has the most complete parser of
ALL python packages around)
